### ISSUE TITLE
pack.mcmeta still uses "examplemod" as its name 

### ISSUE THREAD

**Issue by Tomatosoupcodes** [Cy4Shot/JED#1]
Title says it all. Examplemod is used instead of mod title in the description part of the pack.mcmeta file right here:
https://github.com/Cy4Shot/JED/blob/main/src/main/resources/pack.mcmeta
EDIT: Yes, this has no functional purpose and seems kinda overcritical. I am just trying to bring this up early on so it isn't overlooked at a later point. This is what early versions and betas are for.

**Comment by WynnKunGz** [comment]
chill out bro, the mod is still in its early versions, and it doesnt matter for now. it's just the description shown in the pack

**Comment by Tomatosoupcodes** [comment]
I know this is an insignificant detail, but this is just something for future consideration. It doesn't need fixing any time soon, and I'm not trying to be troll. Again, it's just something that should be fixed in the future.

**Comment by WynnKunGz** [comment]
it is indeed an insignificant detail and i think it's already planned to be fixed and stuff cuz it's an insignificant detail so it isnt being fixed now. the fact that the mod is still in its early versions

**Comment by Tomatosoupcodes** [comment]
As long as it's planned to be fixed. I saw that it was released on CurseForge and kinda assumed it was out of early development. But if it's still not fully finished, then no worries. If you think that the authors are aware of this, I can close the issue if you want.

**Comment by WynnKunGz** [comment]
ill just ask the author then, i know him
edit : he fixed it. should be released in the next update

**Comment by Cy4Shot** [comment]
> Title says it all. Examplemod is used instead of mod title in the description part of the pack.mcmeta file right here: https://github.com/Cy4Shot/JED/blob/main/src/main/resources/pack.mcmeta EDIT: Yes, this has no functional purpose and seems kinda overcritical. I am just trying to bring this up early on so it isn't overlooked at a later point. This is what early versions and betas are for.

Oops haha, will be fixed in 1.0.2 :D

**Comment by Tomatosoupcodes** [comment]
Thanks! I know this was a minor issue (not even a bug really) but with such a community-driven mod, every detail counts (also my OCD got to me lol). Can't wait for the new update!
